var species=[], session=[], idx=0, score=0, selectedDecision='', evaluated=false;
function $(id){return document.getElementById(id)}
function norm(s){return (s||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function show(id){['guidePanel','quizSetupPanel','quizPanel','statsPanel'].forEach(function(p){$(p).classList.add('hidden')});$(id).classList.remove('hidden');document.body.classList.toggle('quizOnly',id==='quizPanel');window.scrollTo(0,0)}
function groups(){var a=['Toutes'];species.forEach(function(s){if(a.indexOf(s.group)<0)a.push(s.group)});return a}
function decisionText(d){return d==='oui'?'Oui, si taille correcte et tir propre':d==='non'?'Non / à laisser':'Selon réglementation, saison et conditions'}
function cardHTML(s){return '<article class="card"><img class="photo" src="'+s.img+'" alt="'+s.name+'"><div class="body"><span class="badge">'+s.group+'</span><div class="name">'+s.name+'</div><div class="latin">'+s.latin+'</div><div class="facts"><div class="fact"><span>Maille</span><b>'+s.maille+'</b></div><div class="fact"><span>Prélever plutôt</span><b>'+s.takeSize+'</b></div><div class="fact"><span>Température</span><b>'+s.temp+'</b></div><div class="fact"><span>Profondeur</span><b>'+s.depth+'</b></div><div class="fact"><span>Taille moy/max</span><b>'+s.avg+' / '+s.max+'</b></div><div class="fact"><span>Décision</span><b>'+decisionText(s.decision)+'</b></div></div><p>📍 <b>Où :</b> '+s.where+'</p><p>🎯 <b>Astuce :</b> '+s.tip+'</p></div></article>'}
function renderGuide(){var q=norm($('search').value),g=$('filter').value||'Toutes';var list=species.filter(function(s){return(g==='Toutes'||s.group===g)&&norm([s.name,s.latin,s.where,s.group,s.tip].join(' ')).indexOf(q)>=0});$('guideGrid').innerHTML='<div class="grid">'+list.map(cardHTML).join('')+'</div>'}
function initGuide(){ $('filter').innerHTML=groups().map(function(g){return '<option>'+g+'</option>'}).join('');renderGuide()}
function shuffle(a){a=a.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=a[i];a[i]=a[j];a[j]=t}return a}
function startQuiz(){var n=parseInt($('quizCount').value,10)||10;session=shuffle(species).slice(0,Math.min(n,species.length));idx=0;score=0;show('quizPanel');renderQuestion()}
function renderQuestion(){if(idx>=session.length)return finishQuiz(false);var s=session[idx];selectedDecision='';evaluated=false;$('qNum').textContent=(idx+1)+'/'+session.length;$('prog').style.width=(idx/session.length*100)+'%';$('miniScore').textContent=score+' pt';var mailleInput=s.mailleQuestion?'<input id="ansMaille" class="input" placeholder="Maille / règle (ex : 23 cm, protégé)" autocomplete="off" style="margin-top:8px">':'<div class="hint">📏 Pas de question maille pour cette carte : réponds nom + tir + habitat.</div>';$('quizCard').innerHTML='<img class="quizImg" src="'+s.img+'" alt="quiz"><div class="quizBody"><div class="question">Qui est-ce ?</div><input id="ansName" class="input" placeholder="Nom de l’espèce" autocomplete="off">'+mailleInput+'<input id="ansHabitat" class="input" placeholder="Où je le trouve ? ex : roche, herbier, sable..." autocomplete="off" style="margin-top:8px"><div class="decisionRow"><button class="btn" data-decision="oui">Je prélève</button><button class="btn" data-decision="non">Je laisse</button><button class="btn" data-decision="selon">Selon conditions</button></div><button class="btn primary full" data-action="validate">Valider / voir réponse</button><div id="answer" class="answer"></div></div>'}
function habitatOK(s,txt){txt=norm(txt);if(!txt)return false;var source=norm((s.where||'')+' '+(s.depth||''));var keys=[];['roche','rocher','faille','trou','digue','sable','herbier','posidonie','pleine eau','surface','tombant','epave','port','grau','etang','vase','fond','large'].forEach(function(k){if(source.indexOf(norm(k))>=0)keys.push(norm(k))});return keys.some(function(k){return txt.indexOf(k)>=0})}
function validate(){if(evaluated)return nextCard();var s=session[idx];var an=norm($('ansName').value);var names=[s.name].concat(s.aliases||[]).map(norm);var goodName=an&&names.some(function(n){return n.indexOf(an)>=0||an.indexOf(n)>=0});var goodMaille=true;if(s.mailleQuestion){var am=norm(($('ansMaille')||{}).value);if(s.mailleKey==='interdit')goodMaille=/(interdit|protege|protege|laisser|non)/.test(am);else if(s.mailleKey==='verifier')goodMaille=/(verif|verifier|selon|variable|doute|zone|carapace)/.test(am);else goodMaille=am.indexOf(String(s.mailleKey))>=0}var goodDecision=(selectedDecision===s.decision)||(s.decision==='selon'&&(selectedDecision==='selon'||selectedDecision==='non'));var goodHabitat=habitatOK(s,$('ansHabitat').value);var maxPts=3+(s.mailleQuestion?1:0);var pts=(goodName?1:0)+(s.mailleQuestion?(goodMaille?1:0):0)+(goodDecision?1:0)+(goodHabitat?1:0);score+=pts;saveStat(s.name,pts,maxPts);evaluated=true;$('miniScore').textContent=score+' pt';var maillePill=s.mailleQuestion?'<span class="pill '+(goodMaille?'ok':'bad')+'">Maille '+(goodMaille?'✅':'❌')+'</span>':'<span class="pill ok">Maille non demandée</span>';$('answer').classList.add('show');$('answer').innerHTML='<div><span class="pill '+(goodName?'ok':'bad')+'">Nom '+(goodName?'✅':'❌')+'</span>'+maillePill+'<span class="pill '+(goodDecision?'ok':'bad')+'">Décision '+(goodDecision?'✅':'❌')+'</span><span class="pill '+(goodHabitat?'ok':'bad')+'">Habitat '+(goodHabitat?'✅':'❌')+'</span><span class="pill ok">+'+pts+'/'+maxPts+' points</span></div><h2>'+s.name+'</h2><div class="latin">'+s.latin+'</div><div class="facts"><div class="fact"><span>Maille</span><b>'+s.maille+'</b></div><div class="fact"><span>Décision guide</span><b>'+decisionText(s.decision)+'</b></div><div class="fact"><span>Prélever plutôt</span><b>'+s.takeSize+'</b></div><div class="fact"><span>Température</span><b>'+s.temp+'</b></div><div class="fact"><span>Profondeur</span><b>'+s.depth+'</b></div><div class="fact"><span>Taille moy/max</span><b>'+s.avg+' / '+s.max+'</b></div></div><p>📍 <b>Où :</b> '+s.where+'</p><p>🎯 <b>Astuce :</b> '+s.tip+'</p><button class="btn gold" data-action="next">Carte suivante</button>'}
function nextCard(){idx++;renderQuestion();window.scrollTo(0,0)}
function finishQuiz(cancelled){show('statsPanel');var total=session.reduce(function(sum,s){return sum+3+(s.mailleQuestion?1:0)},0);var pct=total?Math.round(score/total*100):0;$('statsPanel').innerHTML='<div class="results"><h2>'+(cancelled?'Session arrêtée':'Résultat de session')+'</h2><p style="font-size:30px;font-weight:950">'+score+' / '+total+' points — '+pct+'%</p><p>'+(pct>=85?'🔥 Très solide.':pct>=65?'👍 Bon niveau, révise tes erreurs.':'📚 Encore un peu de révision avant sortie.')+'</p><button class="btn primary" data-action="quizSetup">Relancer un quiz</button> <button class="btn" data-action="guide">Retour guide</button></div>'}
function safeStoreGet(){try{return JSON.parse(localStorage.getItem('chasseStats')||'{}')}catch(e){return{}}}
function saveStat(name,pts,max){try{var st=safeStoreGet();if(!st[name])st[name]={pts:0,max:0,tries:0};st[name].pts+=pts;st[name].max+=max;st[name].tries++;localStorage.setItem('chasseStats',JSON.stringify(st))}catch(e){}}
function renderStats(){show('statsPanel');var st=safeStoreGet();var rows=Object.entries(st).sort(function(a,b){return(a[1].pts/a[1].max)-(b[1].pts/b[1].max)});$('statsPanel').innerHTML='<div class="results"><h2>📊 Statistiques</h2>'+(rows.length?'<div class="grid">'+rows.map(function(r){var n=r[0],v=r[1];return'<div class="fact"><b>'+n+'</b><span>'+v.pts+'/'+v.max+' points • '+v.tries+' passages • '+Math.round(v.pts/v.max*100)+'%</span></div>'}).join('')+'</div>':'<p>Aucune session pour le moment.</p>')+'<button class="btn red full" data-action="clearStats">Effacer les stats</button></div>'}
function handleAction(act){if(act==='guide'){show('guidePanel');renderGuide()}else if(act==='quizSetup'){show('quizSetupPanel')}else if(act==='stats'){renderStats()}else if(act==='startQuiz'){startQuiz()}else if(act==='validate'){validate()}else if(act==='next'){nextCard()}else if(act==='quitQuiz'){finishQuiz(true)}else if(act==='clearStats'){localStorage.removeItem('chasseStats');renderStats()}}
document.addEventListener('click',function(e){var t=e.target.closest('[data-action],[data-decision]');if(!t)return;e.preventDefault();if(t.dataset.decision){selectedDecision=t.dataset.decision;document.querySelectorAll('[data-decision]').forEach(function(b){b.classList.remove('selected')});t.classList.add('selected');return}handleAction(t.dataset.action)},false);
document.addEventListener('input',function(e){if(e.target&&e.target.id==='search')renderGuide()});
document.addEventListener('change',function(e){if(e.target&&e.target.id==='filter')renderGuide()});
fetch('poissons.json').then(function(r){return r.json()}).then(function(data){species=data;initGuide()}).catch(function(err){document.body.innerHTML='<div class="wrap"><div class="results"><h2>Erreur de chargement</h2><p>Le fichier poissons.json doit être envoyé avec index.html, app.js, style.css et le dossier images.</p></div></div>'});
